title: "USDT HUB"
description: "A Chinese-language portal for getting, using, comparing, and understanding USDT"
lang: zh-CN
url: "https://makoshan.github.io"
baseurl: "/usdthub"
markdown: kramdown
theme: null
source: site
destination: docs
exclude:
  - __pycache__
  - .git
  - .gitignore
  - .bundle
  - docs
  - Gemfile
  - Gemfile.lock
  - markdown
  - README.md
  - scripts
  - vendor
plugins: []
